name: 'Genshin daily checkin'
description: 'Genshin daily checkin'
on:
  schedule:
    - cron: "0 7 * * *"
runs:
  using: 'docker'
  image: 'yindan/genshinhelper:latest'
  env:
    COOKIE_HOYOLAB: ${{ secrets.COOKIE_HOYOLAB }}
