name: 'Genshin daily checkin'
# Controls when the action will run. 
on:
  schedule:
  - cron: "0 7 * * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Genshin-Check:
    runs-on: ubuntu-latest
    steps:
    - run: "docker run -d --name=genshinhelper -e COOKIE_HOYOLAB=\"${{ secrets.COOKIE_HOYOLAB }}\" yindan/genshinhelper:1.4.0 && sleep 20 && docker logs genshinhelper"
#       - uses: docker://yindan/genshinhelper:latest
#         env:
#           COOKIE_HOYOLAB: ${{ secrets.COOKIE_HOYOLAB }}
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Use local my-action
#         uses: ./.github/actions/action.yml
