name: 'Genshin daily checkin'
# Controls when the action will run. 
on:
  schedule:
  - cron: "0 7 * * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Genshin-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./action.yml
